# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b9e804bb1d059b0395d23ded526512f9bcc829d756e7cfc17bbe87d3c88b4ad5143dc935b6bdc0dc07bf7dace970d567363fb51a8a6aad312621d8e8b6baf64

test:
  secret_key_base: 328633df8aa7a99e70b40839a7e64edf4442463f543ab903e61d6f4f13f75690670c19d39d9e7e1a4e7248d03086bdfa8298b2c0712472c6b3facaa34833f645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
